### ISSUE TITLE
Does this work with remote servers?

### ISSUE THREAD

**Issue by thedoglett** [VineCode/Sass.novaextension#1]
I've got this working fine with Nova on my iMac for local development and was just wondering if its possible when I edit scss files directly on a remote server to have the extension compile them?

Thanks for creating a cracking extension for Nova. :)

**Comment by vinecode-andy** [comment]
Hi, thanks for your feedback. Apologies it took so long to get back to you. My knowledge of the Nova API is pretty limited so although it may be possible to compile on remote this is not something I am looking to add. I would have loved Panic to have added these feature into the Editor, but unfortunately they didn't. Compiling  SCSS and JS was a show stopped for me moving to Nova which is why I whipped up this extension.
