### ISSUE TITLE
Compile to remote

### ISSUE THREAD

**Issue by jwssnr** [VineCode/Sass.novaextension#11]
I could not get the extension to compile on a remote server.

**Comment by vinecode-andy** [comment]
#1, Hi, thanks for your feedback. Apologies it took so long to get back to you. My knowledge of the Nova API is pretty limited so although it may be possible to compile on remote this is not something I am looking to add. I would have loved Panic to have added these feature into the Editor, but unfortunately they didn't. Compiling SCSS and JS was a show stopped for me moving to Nova which is why I whipped up this extension.

**Comment by jwssnr** [comment]
Thanks for your answer, Andy
I understand that. I also don't understand why Panic wants to sell us such a rudimentarily equipped editor.
