### ISSUE TITLE
Settings per Project

### ISSUE THREAD

**Issue by radogado** [VineCode/Sass.novaextension#18]
Hi, can you please add project-specific settings, so we can disable it on certain projects. Thanks.

**Comment by JohnWickham** [comment]
+1 for this.

I don’t see anything in the [Nova Extensions API](https://docs.nova.app/extensions/) that would enable explicit per-project settings, but it could make sense to use [Activation Events ](https://docs.nova.app/extensions/#activation-events) with a preference for only running the extension in projects that contain a certain config file (or sass directory?)

**Comment by JohnWickham** [comment]
Following up because I think I was _totally_ wrong about this: the `config-workspace` fields make this possible. Panic’s own HTML Validator extension makes use of this.

When I have time, I’ll write a fork for per-project sass settings. In the meantime, I’ve been using a Run script for my project that uses `sass --watch` to automatically compile sass on save. In practice this is almost as good as having an extension do it automatically.

**Comment by vinecode-andy** [comment]
@JohnWickham Perfect ! Thanks for the Pull Request. The only change I wanted to make was for the default be be Compile on Save enabled, so I have switched the workspaceEnable to workspaceDisable so it can be turned off per project.

**Comment by vinecode-andy** [comment]
@radogado @JohnWickham Version 1.5 has just been pushed to the Nova Library with this update. Let me know if it works OK for you. Thanks

**Comment by radogado** [comment]
Seems to work, thanks!
