### ISSUE TITLE
Saving a .scss file that is imported into another .scss file doesn't compile the parent .scss file

### ISSUE THREAD

**Issue by philbuchanan** [VineCode/Sass.novaextension#2]
### Steps to Reproduce

Create 2 files:

`style.scss`

```scss
@import "scss/component/imported";
```

`scss/component/_imported.scss`

```scss
body {
    background-color: red;
}
```

Make a change to `scssscss/component/_imported.scss` and save.

When making an edit in `/scss/component/_imported.scss` and saving the file, I would expect `style.scss` to compile. Instead I must open and save `style.css` independently for the changes to compile.

**Comment by vinecode-andy** [comment]
Ah I see the issue. For my use case I only ever nest the _xyz.scss files one directory level down. 

e.g. 
style.scss
scss/_imported.scss

For me increasing the parent lookup would cause issues, I have other libraries at the parent level so it would start compiling bootstrap etc. I think that the best option would be to add a preference so that you can choose where to run the scss compiler. e,g, For Whole Project, One Level Up, Two Levels Up etc. 

Would this resolve your issue ?

Thanks

**Comment by philbuchanan** [comment]
I think that would work. Or let me specify specific files to watch. Similar to how `sass --watch` works.

Not sure how possible it would be to automatically ignore locations in a .gitignore file in the project, if I set "Whole Project". That could solve the libraries issue if you have a `node_modules` folder or something.

**Comment by scottyzwilson** [comment]
I just dove into Nova tonight. I think either of your ideas would work. But like Phil, I often use the 7-1-1 pattern for my scss and keep the root scss and compiled css files outside the scss tree. So the source code ends up two levels down from the master file that should be watched. Hope that makes sense. I think having the ability to select where the compiler runs would be perfect. Thanks for writing this extension.

**Comment by vinecode-andy** [comment]
Pushed an update which adds a preference to manually set the path that an update will be performed on, relative to the workspace directory. Let me know if this helps.

**Comment by kbanse** [comment]
Thanks for the extension, only issue I see is that that manual path may change based on project. 

Any way of setting it up to have all imported files in a single subfolder (ie. components or maybe also set in preferences), then travel up and look for a filename (maybe set in preferences) like filename.scss , then compile it one level up as filename.css so the structure would be something along the lines of:

style.css
--scss/
----style.scss
----components/
------_imported.scss

that way you wouldn't have to worry about different folder names or other files since it would only look for the one set in preferences. and would only use the folder names scss and the "default" one set in preferences.

Just a thought.

**Comment by scottyzwilson** [comment]
Yeah, I agree with @kbanse in that I'm working on several different projects—most of which I don't get to control the directory structure. But I still the suggestion might be too prescriptive. For me, I've used both of these approaches:

--styles
----style.css
----style.scss
----scss/
------components/
--------_imported.scss

— OR —

--styles
----css
------style.css
----scss/
------style.scss
------components/
--------_imported.scss


Personally, I think its ok to rely on the scss code to explicitly declare paths. So, the plugin needn't guess where and how far to descend in order to compile...the files should always use proper include paths relative to the parent scss file. In this case, similar to watch-sass, the plugin would just need to know the parent/source scss file and where to drop the target compiled file. But per project, which might be trickier than it seems :-/

**Comment by vinecode-andy** [comment]
@kbanse @scottyzwilson HI Guys, thanks for your feedback. I have been looking at preferences on a per project basis but not quite figured out the Nova API to do this, I think you can manually add a .nova/Configuration.json file and add them in here. I have quite limited time to work on this at the moment so don't think that this is something I can add too soon. 

One feature that has been added is an Output Path preference, this may help with the structures you have given. e.g.

```
Update Path: styles/scss
Output Path: css/
```
or 
```
Update Path: scss/
Output Path: /
```

This will take from the update and compile into the output. 

Thanks

**Comment by JohnWickham** [comment]
Pull request #19 includes per-project preferences
